Modules/CodeEduUser/Http/routes.php
<?php

Route::group(['as' => 'codeeduuser.',
    'middleware' => ['auth', config('codeeduuser.middleware.isVerified')]
], function () {

    Route::group(['prefix' => 'admin', 'middleware' => 'auth.resource'], function () {
        Route::resource('users', 'UsersController');
        Route::resource('roles', 'RolesController');
        Route::get('roles/{role}/permission', 'RolesController@editPermission')->name('roles.permission.edit');
        Route::put('roles/{role}/permission', 'RolesController@updatePermission')->name('roles.permission.update');
    });

    Route::get('users/settings', 'UserSettingsController@edit')->name('user_settings.edit');
    Route::put('users/settings', 'UserSettingsController@update')->name('user_settings.update');

    Route::get('email-verification/error', 'UserConfirmationController@getVerificationError')->name('email-verification.error');
    Route::get('email-verification/check/{token}', 'UserConfirmationController@getVerification')->name('email-verification.check');

});

Modules/CodeEduUser/Models/User.php
<?php

namespace CodeEduUser\Models;

use Bootstrapper\Interfaces\TableInterface;
use Collective\Html\Eloquent\FormAccessible;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Cashier\Billable;

class User extends Authenticatable implements TableInterface
{
    use Notifiable;
    use SoftDeletes;
    use FormAccessible;
    use Billable;

    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function formRolesAttribute()
    {
        return $this->roles->pluck('id')->all();
    }

    public static function generatePassword($password = null)
    {
        return !$password ? bcrypt(str_random(8)) : bcrypt($password);
    }

    /**
     * A list of headers to be used when a table is displayed
     *
     * @return array
     */
    public function getTableHeaders()
    {
        return ['#', 'Nome', 'E-mail', 'Roles'];
    }

    /**
     * Get the value for a given header. Note that this will be the value
     * passed to any callback functions that are being used.
     *
     * @param string $header
     * @return mixed
     */
    public function getValueForHeader($header)
    {
        switch ($header) {
            case '#':
                return $this->id;
            case 'Nome':
                return $this->name;
            case 'E-mail':
                return $this->email;
            case 'Roles':
                return $this->roles->implode('name', ' | ');
        }
    }


    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    /**
     * @param Collection /string $role
     * @return boolean
     */
    public function hasRole($role)
    {
        return is_string($role) ? $this->roles->contains('name', $role) : (boolean)$role->intersect($this->roles)->count();
    }

    public function isAdmin()
    {
        return $this->hasRole(config('codeeduuser.acl.role_admin'));
    }

    public function routeNotificationForNexmo()
    {
        return "5518996213845";
    }
}

Modules/CodeEduUser/Http/Controllers/UsersController.php
<?php

namespace CodeEduUser\Http\Controllers;

use CodeEduUser\Annotations\Mapping as Permission;
use CodeEduUser\Http\Requests\UserDeleteRequest;
use CodeEduUser\Http\Requests\UserRequest;
use CodeEduUser\Repositories\RoleRepository;
use CodeEduUser\Repositories\UserRepository;

/**
 * @Permission\Controller(name="user-admin", description="Administração de Usuários")
 */
class UsersController extends Controller
{
    /**
     * @var UserRepository
     */
    private $repository;
    /**
     * @var RoleRepository
     */
    private $roleRepository;

    /**
     * UsersController constructor.
     *
     * @var \CodeEduUser\Repositories\UserRepository
     */
    public function __construct(UserRepository $repository, RoleRepository $roleRepository)
    {
        $this->repository = $repository;
        $this->roleRepository = $roleRepository;
    }

    /**
     * Display a listing of the resource.
     * @Permission\Action(name="list", description="Ver listagem de usuários")
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = $this->repository->paginate(10);
//        $users = User::onlyTrashed()->paginate(10);
        return view('codeeduuser::users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     * @Permission\Action(name="store", description="Criar usuários")
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = $this->roleRepository->all()->pluck('name', 'id');
        return view('codeeduuser::users.create', compact('roles'));
    }

    /**
     * @param UserRequest $request
     * @Permission\Action(name="store", description="Criar usuários")
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(UserRequest $request)
    {
        $this->repository->create($request->all());
        $url = $request->get('redirect_to', route('codeeduuser.users.index'));
        $request->session()->flash('message', 'Usuário Cadastrado com sucesso.');

        return redirect()->to($url);
    }

    /**
     * Show the form for editing the specified resource.
     * @Permission\Action(name="update", description="Atualizar usuários")
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) //Route Model Binding
    {
        $user = $this->repository->find($id);
        $roles = $this->roleRepository->all()->pluck('name', 'id');
        return view('codeeduuser::users.edit', compact('user', 'roles'));
    }

    /**
     * @Permission\Action(name="update", description="Atualizar usuários")
     * @param UserRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UserRequest $request, $id)
    {
        $data = $request->except(['password']);
        $this->repository->update($data, $id);
        $url = $request->get('redirect_to', route('codeeduuser.users.index'));
        $request->session()->flash('message', 'Usuário Alterado com sucesso.');

        return redirect()->to($url);
    }

    /**
     * Remove the specified resource from storage.
     * @Permission\Action(name="destroy", description="Excluír usuários")
     * @param UserDeleteRequest $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(UserDeleteRequest $request, $id)
    {
        $this->repository->delete($id);
        \Session::flash('message', 'Usuário Deletado com sucesso.');

        return redirect()->to(\URL::previous());
    }

}

Modules/CodeEduUser/resources/views/users/_form.blade.php
{!! Form::hidden('redirect_to', URL::previous()) !!}

{!! Html::openFormGroup('name', $errors) !!}
    {!! Form::label('name', 'Nome', ['class' => 'control-label']) !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
    {!! Form::error('name', $errors) !!}
{!! Html::closeFormGroup() !!}

{!! Html::openFormGroup('email', $errors) !!}
    {!! Form::label('email', 'E-mail', ['class' => 'control-label']) !!}
    {!! Form::text('email', null, ['class' => 'form-control']) !!}
    {!! Form::error('email', $errors) !!}
{!! Html::closeFormGroup() !!}

{!! Html::openFormGroup('roles.*', $errors) !!}
{!! Form::label('roles[]', 'Descrição', ['class' => 'control-label']) !!}
{!! Form::select('roles[]', $roles, null, ['class' => 'form-control', 'multiple' => true]) !!}
{!! Form::error('roles.*', $errors) !!}
{!! Html::closeFormGroup() !!}

Modules/CodeEduUser/resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h3>Novo Usuário</h3>

            {!! Form::open(['route' => 'codeeduuser.users.store', 'class' => 'form']) !!}

            @include('codeeduuser::users._form')


            {!! Html::openFormGroup() !!}
            {!! Button::primary('Criar Usuário')->submit() !!}
            {!! Html::closeFormGroup() !!}

            {!! Form::close() !!}
        </div>
    </div>
@endsection

Modules/CodeEduUser/resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h3>Editar Usuário</h3>
            {!! Form::model($user, ['route' => ['codeeduuser.users.update', 'category' => $user->id], 'class' => 'form', 'method' => 'PUT']) !!}

            @include('codeeduuser::users._form')

            {!! Html::openFormGroup() !!}
            {!! Button::primary('Salvar Usuário')->submit() !!}
            {!! Html::closeFormGroup() !!}

            {!! Form::close() !!}
        </div>
    </div>
@endsection

Modules/CodeEduUser/resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h3>Listagem de Usuários</h3>
            {!! Button::primary('Novo Usuário')->asLinkTo(route('codeeduuser.users.create')) !!}
        </div>
        <br/>
        <div class="row">
            {!! Form::model(compact('search'), [ 'class' => 'form-inline', 'method' => 'GET']) !!}
            {!! Form::label('search', 'Perquisar por Nome', ['class' => 'control-label']) !!}
            {!! Form::text('search', null, ['class' => 'form-control']) !!}

            {!! Button::primary('Buscar')->submit() !!}
            {!! Form::close() !!}
        </div>

        <div class="row">
            {!!
            Table::withContents($users->items())->striped()
            ->callback('Ações', function($field, $user){
                $linkEdit = route('codeeduuser.users.edit', ['user' => $user->id]);
                $linkDestroy = route('codeeduuser.users.destroy', ['user' => $user->id]);
                $deleteForm =  "deleteForm-{$user->id}";
                $form =  Form::open(['route' => ['codeeduuser.users.destroy', 'user' => $user->id],

                                    'method' => 'DELETE', 'id'=> $deleteForm, 'style' => 'display:none'])
                                    . Form::close();
                $anchorDestroy = Button::link('Excluir')->asLinkTo($linkDestroy)->addAttributes([
                                  'onclick' => "event.preventDefault(); document.getElementById(\"{$deleteForm}\").submit();"
                                  ]);
                if($user->id == \Auth::user()->id){
                    $anchorDestroy->disable();
                }
                return "<ul class=\"list-inline\">".
                        "<li>".Button::link('Editar')->asLinkTo($linkEdit)."</li>".
                        "<li>|</li>".
                        "<li>".$anchorDestroy."</li>".
                       "</ul>" . $form;
            })
            !!}
            {{$users->links()}}
        </div>
    </div>
@endsection